// <auto-generated />
namespace StudentRanking.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class Update3 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Update3));
        
        string IMigrationMetadata.Id
        {
            get { return "201505221815332_Update3"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
